replicaCount: 4
revisionHistoryLimit: 3

image:
  repository: gcr.io/heptio-images/ks-guestbook-demo
  tag: 0.2

livenessProbe:
  initialDelaySeconds:: 3
  periodSeconds: 3

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi